kind: BuildConfig
apiVersion: v1
metadata:
  name: "wordpress"
  labels:
    app: "wordpress"
spec:
  triggers:
  - type: ConfigChange
  - type: ImageChange
  source:
    type: Dockerfile
    dockerfile: |-
      FROM wordpress
      RUN sed -i "s/80/8080/g" /etc/apache2/ports.conf
      RUN sed -i "s/80/8080/g" /etc/apache2/sites-available/000-default.conf
      RUN sed -i "s/^ServerTokens OS$/ServerTokens Prod/" /etc/apache2/conf-enabled/security.conf
      RUN sed -i "s/^ServerSignature On$/ServerSignature Off/" /etc/apache2/conf-enabled/security.conf
      RUN echo "UseCanonicalName On" >> /etc/apache2/conf-enabled/security.conf
      RUN { \
      echo 'error_log=/var/log/apache2/php-error.log'; \
      echo 'log_errors=On'; \
      echo 'display_startup_errors=Off'; \
      echo 'date.timezone=UTC'; \
      echo 'session.cache_limiter = nocache'; \
      echo 'session.auto_start = 0'; \
      echo 'expose_php = off'; \
      echo 'allow_url_fopen = off'; \
      echo 'magic_quotes_gpc = off'; \
      echo 'register_globals = off'; \
      echo 'display_errors=Off'; \
      } > /usr/local/etc/php/conf.d/php.ini
      EXPOSE 8080
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: DockerImage
        name: wordpress:5-apache
    type: Docker
  triggers:
  - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: "wordpress-img:latest"
    imageLabels:
    - name: io.k8s.display-name
      value: WordPress
    - name: io.k8s.description
      value: WordPress application and S2I builder.
    - name: io.openshift.s2i.scripts-url
      value: image:///opt/app-root/s2i
    - name: io.s2i.scripts-url
      value: image:///opt/app-root/s2i
    - name: io.openshift.tags
      value: builder,php,wordpress
