apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mariadb
      annotations:
        appuio.ch/backupcommand: /bin/bash -c 'mysqldump -uroot -p"${MYSQL_ROOT_PASSWORD}" --all-databases'
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          exec:
            command:
            - "/bin/sh"
            - "-i"
            - "-c"
            - mysql -h 127.0.0.1 -uroot -p"${MYSQL_ROOT_PASSWORD}" -D mysql -e 'SELECT 1'
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 30
          tcpSocket:
            port: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: password
        volumeMounts:
        - name: data
          mountPath: "/var/lib/mysql"
          subPath: mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "mariadb-pvc"
